project:
  type: website
  output-dir: docs

website:
  title: "Philipp Poyntner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index.qmd#research
        text: Research
      - href: index.qmd#teaching
        text: Teaching
      - href: index.qmd#media
        text: Media
      - href: index.qmd#cv
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

