---
title: "Miscellaneous"
about:
  template: jolla
format: html
engine: knitr
---

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

## Consultancy experience:

::: justify
International Finance Corporation (World Bank): Development of a python code to automate data download

European Centre for Social Welfare Policy and Research: Update of the Tax-Benefit Microsimulation Models SORESI & EUROMOD

Austrian National Bank (OeNB): Various research projects
:::

## Referee service:

::: justify
<<<<<<< HEAD
Empirica, Empirical Economics, German Economic Review, OeNB Anniversary Fund, Oxford Bulletin of Economics and Statistics, Real Estate Economics, Review of World Economics
=======
Empirica, Empirical Economics, German Economic Review, OeNB Anniversary Fund,, Oxford Bulletin of Economics and Statistics, Real Estate Economics, Review of World Economics
>>>>>>> fa5cd6708c70e9a447c6cc479249e1ab97565719
:::

## Other:

::: justify
I made a little <a href="https://twitter.com/grillplatzwien">twitter bot</a> that alerted followers when registration for the highly demanded barbecue spots at Viennas Danube island has opened (hibernated now as the registration service is back to the usual schedule).
:::

::: justify
Occasionally, I play clarinet with the band "Dritte Hand", specializing in Donaurock and Stonerwalzer. Check out their new album <a href="https://open.spotify.com/album/36vuPMDywVFsP6hKR68JJv?si=KYg2J_mASq-l-acPI5IJ8w">Olle Viecha Olle Fisch</a>.
:::

## Disclaimer:

::: justify
This website is made with <a href="https://quarto.org/">Quarto</a> and hosted on <a href="https://github.com/PhilippPoyntner/website">Github</a>.

<body>

::: {#result}
:::

```{=html}
<script>
      var date = document.lastModified;
      date=date.slice(0, -9); 
      document.getElementById("result").innerHTML = "The website was last updated on: " + date;
   </script>
```
</body>
:::
