---
title: "News"
about:
  template: jolla
format: html
engine: knitr
---

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

::: justify
-   04/2025: I will present "How do monetary policy decisions relate to price changes in housing markets?" at the SCEUS Young Scholars Workshop in May 2025
-   04/2025: I will present "The international spillovers of corporate bonds purchases" at the Workshop on Credit Market Interventions at the Bank of England in May 2025
-   09/2024: <a href="https://www.diepresse.com/18877391/wie-geldpolitik-die-immobilienpreise-beeinflusst"> Wie Geldpolitik die Immobilienpreise beeinflusst </a> ("How monetary policy influences property prices") with Sofie R. Waltl, a blog contribution to the NOeGs "Der ökonomische Blick", appeared in "Die Presse" (German).
-   05/2024: My thesis was awarded the <a href="https://www.wu.ac.at/en/economics/research/hanns-abele-prize">Hanns-Abele Prize 2024</a>
-   04/2024: I will present "Heat and Construction Workers’ Health" at EUHEA in Vienna in July 2024
-   04/2024: I will present "How do monetary policy decisions relate to price changes in housing markets?" at the 3rd Workshop on Residential Housing Markets in Vienna in June 2024
-   04/2024: I will present "How do monetary policy decisions relate to price changes in housing markets?" at the 38th IARIW General Conference ind London in August 2024
-   03/2024 LIS issues a quarterly newsletter "Inequality Matters", where I contributed a note on "Monetary Policy, Housing and Inequality" for<a href="https://www.lisdatacenter.org/wp-content/uploads/files/nl-2024-29.pdf"> Issue No. 29 (March 2024)</a>
-   01/2024: I will present "Firm-Level Consequences of Corporate Quantitative Easing" at the ASSA Annual Meeting poster session in San Francisco in January 2024
-   12/2023: My dissertation was awarded with the WU Vienna "Research bonus for outstanding dissertations"
-   12/2023: I have received a performance bonus for young scientists at WU Vienna for the Publication "Keeping up with the Novaks? Income distribution as a determinant of household debt in CESEE"
-   12/2023: I will present "Firm-Level Consequences of Corporate Quantitative Easing" at the 17th SEE Economic Research Workshop, Tirana
-   11/2023: From November 2023 onward, I am joining the <a href="https://www.plus.ac.at/economics/?lang=en"> Department of Economics of the Paris Lodron University Salzburg </a> as a Senior Scientist
-   10/2023: I completed the PhD Degree Program in Economics and Social Sciences at the Vienna University of Economics and Business (passed with honors) with the thesis "Essays on monetary policy"
-   05/2023: From July to September 2023, I will join the Bank of England's Financial Stability Strategy & Projects division as part of a PhD internship
-   03/2023: I will visit LIS / LISER in November 2023 as part of the <a href="https://www.lisdatacenter.org/projects/lis2er-initiative/visitors/"> (LIS)\^2ER visiting fellowship programme</a>
-   02/2023: "Quantitative Easing and Wealth Inequality: The Asset Price Channel" is now online at the <em>Oxford Bulletin of Economics and Statistics</em> <a href="https://onlinelibrary.wiley.com/doi/10.1111/obes.12543"> (Open Access)</a>
-   01/2023: "Quantitative Easing and Wealth Inequality: The Asset Price Channel" has been accepted at the <em>Oxford Bulletin of Economics and Statistics</em>!
:::
